/// Represents a polkadot or parachain event as an emoji.
/// (Obviously this is only indicative and effects of an extrinsic
/// depends on the definition of that parachain's runtime.)
///
/// These can't be represented as 'char' because some emojis span more
/// than one codepoint.
pub fn event_emoji(pallet: &str, variant: &str) -> Option<&'static str> {
	match (pallet, variant) {
		("AcalaOracle", "NewFeedData") => Some("🔮"),
		("Assets", "ApprovedTransfer") => Some("💱"),
		("AMMRoute", "Traded") => Some("💱"),
		("AMM", "Traded") => Some("💱"),
		("Assets", "Transferred") => Some("💱"),
		("AMM", "LiquidityAdded") => Some("📈"),
		("Assets", "Issued") => Some("🐣"),
		("Assets", "ApprovalCancelled") => Some("⚠️"),
		("Attestation", "AttestationCreated") => Some("✒️"),
		("Assets", "Burned") => Some("🔥"),
		("AMM", "LiquidityRemoved") => Some("📉"),
		("Balances", "Unreserved") => Some("🔓"),
		("Balances", "BalanceSet") => Some("🏦"),
		("Balances", "Deposit") => Some("🏦"),
		("Balances", "Transfer") => Some("🔀"),
		("Balances", "Endowed") => Some("🏦"),
		("Balances", "Withdraw") => Some("💰"),
		("Balances", "DustLost") => Some("🧹"),
		("Balances", "Reserved") => Some("🔒"),
		("Common", "TokenPropertySet") => Some("🔧"),
		("CollatorRewards", "CollatorRewarded") => Some("🥕"),
		("Currencies", "Withdrawn") => Some("💰"),
		("Currencies", "Transferred") => Some("🔀"),
		("Currencies", "Deposited") => Some("💵"),
		("CrowdloanRewards", "RewardsPaid") => Some("🥕"),
		("Crowdloan", "HandleBidResult") => Some("🔮"),
		("ChainBridge", "VoteFor") => Some("☑"),
		("DmpQueue", "ExecutedDownward") => Some("📨"),
		("Dex", "Swap") => Some("💱"),
		("Democracy", "Voted") => Some("☑"),
		("DappsStaking", "RewardDestination") => Some("🥕"),
		("Datalog", "NewRecord") => Some("✒️"),
		("DicoOracle", "NewLockedPrice") => Some("🔮"),
		("DappsStaking", "Reward") => Some("🥕"),
		("DappsStaking", "BondAndStake") => Some("🔒"),
		("Ethereum", "Executed") => Some("🧠"),
		("EVM", "Executed") => Some("⚙️"),
		("EVM", "Log") => Some("🪵"),
		("Farming", "Withdrawn") => Some("🧑‍🌾"),
		("Farming", "WithdrawClaimed") => Some("🧑‍🌾"),
		("Farming", "RewardPaid") => Some("🥕"),
		("Farming", "Claimed") => Some("🧑‍🌾"),
		("Farming", "AssetsDeposited") => Some("🧑‍🌾"),
		("Farming", "Deposited") => Some("🧑‍🌾"),
		("FlexibleFee", "FlexibleFeeExchanged") => Some("💱"),
		("FuelTanks", "AccountAdded") => Some("👶"),
		("FuelTanks", "CallDispatched") => Some("⚗️"),
		("Homa", "Minted") => Some("👶"),
		("Homa", "RequestedRedeem") => Some("⏸️"),
		("Homa", "RedeemedByFastMatch") => Some("💰"),
		("Homa", "RedeemRequestCancelled") => Some("⚠️"),
		("Hrmp", "OpenChannelRequested") => Some("📢"),
		("Incentives", "WithdrawDexShare") => Some("📉"),
		("Incentives", "ClaimRewards") => Some("🥕"),
		("ImOnline", "HeartbeatReceived") => Some("💓"),
		("Lighthouse", "BlockReward") => Some("🥕"),
		("Loans", "DistributedSupplierReward") => Some("🥕"),
		("Loans", "DistributedBorrowerReward") => Some("🥕"),
		("LiquidStaking", "StakingLedgerUpdated") => Some("✒️"),
		("Loans", "Deposited") => Some("💲"),
		("Loans", "PositionUpdated") => Some("🤖"),
		("Loans", "Redeemed") => Some("💰"),
		("Loans", "RepaidBorrow") => Some("⭐"),
		("Loans", "Borrowed") => Some("💰"),
		("Loans", "RewardPaid") => Some("🥕"),
		("Mining", "MiningResourceMintedTo") => Some("⛏️"),
		("MultiTokens", "TokenCreated") => Some("👶"),
		("MultiTokens", "CollectionAccountCreated") => Some("👶"),
		("MultiTokens", "TokenAccountCreated") => Some("👶"),
		("MultiTokens", "Minted") => Some("⛏️"),
		("MultiTokens", "TokenAccountDestroyed") => Some("🔥"),
		("MultiTokens", "Transferred") => Some("🔀"),
		("Multisig", "MultisigApproval") => Some("👥"),
		("Multisig", "NewMultisig") => Some("👥"),
		("Multisig", "MultisigExecuted") => Some("⚙️"),
		("MoonbeamOrbiters", "OrbiterRewarded") => Some("🥕"),
		("NominationPools", "PaidOut") => Some("💰"),
		("NominationPools", "Bonded") => Some("🔒"),
		("NominationPools", "Unbonded") => Some("🔓"),
		("Nft", "TransferedNft") => Some("🎨"),
		("Oracle", "NewPrice") => Some("🔮"),
		("Oracle", "NewFeedData") => Some("🔮"),
		("PolkadotXcm", "AssetsTrapped") => Some("⚠️"),
		("PolkadotXcm", "Sent") => Some("📩"),
		("ParachainStaking", "Delegation") => Some("👥"),
		("ParachainSystem", "DownwardMessagesReceived") => Some("📨"),
		("ParachainSystem", "DownwardMessagesProcessed") => Some("📨"),
		("ParachainStaking", "DelegationRevocationScheduled") => Some("⏰"),
		("ParachainStaking", "ReservedForParachainBond") => Some("🔒"),
		("ParachainStaking", "CollatorChosen") => Some("🎲"),
		("ParachainStaking", "NewRound") => Some("👶"),
		("ParachainStaking", "AutoCompoundSet") => Some("🔧"),
		("ParachainStaking", "DelegatorLeftCandidate") => Some("👻"),
		("ParachainStaking", "DelegationRevoked") => Some("⚠️"),
		("ParachainStaking", "DelegationKicked") => Some("💀"),
		("ParachainStaking", "DelegatorLeft") => Some("👻"),
		("PolkadotXcm", "Attempted") => Some("⚗️"),
		("ParachainStaking", "DelegationIncreased") => Some("📈"),
		("ParaInclusion", "CandidateIncluded") => Some("⚓"),
		("ParaInclusion", "CandidateBacked") => Some("🤠"),
		("ParachainStaking", "Compounded") => Some("💲"),
		("ParachainStaking", "Rewarded") => Some("🥕"),
		("PhalaBasePool", "NftCreated") => Some("🎨"),
		("PhalaRegistry", "WorkerUpdated") => Some("⚙️"),
		("PhalaRegistry", "InitialScoreSet") => Some("⚙️"),
		("PhalaComputation", "BenchmarkUpdated") => Some("⚙️"),
		("PhalaComputation", "WorkerEnterUnresponsive") => Some("⚠️"),
		("PhalaComputation", "SessionSettled") => Some("⚙️"),
		("PhalaComputation", "WorkerExitUnresponsive") => Some("⚠️"),
		("PhalaStakePoolv2", "RewardReceived") => Some("🥕"),
		("PhalaBasePool", "Withdrawal") => Some("💰"),
		("PhalaVault", "Contribution") => Some("💲"),
		("PhalaVault", "PoolCreated") => Some("⚙️"),
		("PhalaWrappedBalances", "Wrapped") => Some("⚙️"),
		("PhragmenElection", "EmptyTerm") => Some("👻"),
		("Proxy", "ProxyExecuted") => Some("👻"),
		("Proxy", "Announced") => Some("👻"),
		("RWS", "NewCall") => Some("👾"),
		("Referenda", "SubmissionDepositRefunded") => Some("💰"),
		("RmrkCore", "NftMinted") => Some("⛏️"),
		("RmrkCore", "NFTBurned") => Some("🔥"),
		("RmrkCore", "PropertySet") => Some("✒️"),
		("RmrkCore", "CollectionCreated") => Some("🎨"),
		("RelayChainInfo", "CurrentBlockNumbers") => Some("✒️"),
		("Sudo", "Sudid") => Some("🤠"),
		("System", "ExtrinsicSuccess") => Some("👍"),
		("System", "ExtrinsicFailed") => Some("⚠️"),
		("System", "NewAccount") => Some("🐣"),
		("Staking", "Unbonded") => Some("🔓"),
		("StableAsset", "BalanceUpdated") => Some("🤖"),
		("StableAsset", "FeeCollected") => Some("🫴"),
		("StableAsset", "TokenSwapped") => Some("💱"),
		("Session", "NewSession") => Some("👶"),
		("Staking", "Chilled") => Some("❄️"),
		("Staking", "ValidatorPrefsSet") => Some("✒️"),
		("Scheduler", "Canceled") => Some("⚠️"),
		("Scheduler", "Scheduled") => Some("📅"),
		("Scheduler", "Dispatched") => Some("⚙️"),
		("Staking", "PayoutStarted") => Some("💎"),
		("Staking", "Rewarded") => Some("🥕"),
		("Staking", "Withdrawn") => Some("🔓"),
		("Staking", "Bonded") => Some("🔒"),
		("Slp", "TimeUnitUpdated") => Some("⏰"),
		("System", "KilledAccount") => Some("🪦"),
		("TransactionPayment", "TransactionFeePaid") => Some("🫴"),
		("Treasury", "Deposit") => Some("🐖"),
		("Treasury", "Spending") => Some("💲"),
		("Treasury", "Burnt") => Some("🔥"),
		("Treasury", "Rollover") => Some("🔄"),
		("Tokens", "DustLost") => Some("🧹"),
		("Tokens", "Withdrawn") => Some("💰"),
		("Tokens", "Deposited") => Some("💲"),
		("Tokens", "Endowed") => Some("💊"),
		("Tokens", "Transfer") => Some("🔀"),
		("Tokens", "Unreserved") => Some("🔓"),
		("Ump", "UpwardMessagesReceived") => Some("📨"),
		("Ump", "ExecutedUpward") => Some("📨"),
		("Uniques", "Burned") => Some("🔥"),
		("Uniques", "Created") => Some("🎨"),
		("Uniques", "Issued") => Some("⛏️"),
		("Utility", "BatchCompleted") => Some("👍"),
		("Utility", "BatchCompletedWithErrors") => Some("⚠️"),
		("Utility", "ItemCompleted") => Some("👍"),
		("Utility", "ItemFailed") => Some("⚠️"),
		("Vesting", "VestingUpdated") => Some("🤖"),
		("Vesting", "Claimed") => Some("💎"),
		("VtokenMinting", "RedeemSuccess") => Some("👍"),
		("VtokenMinting", "Minted") => Some("⛏️"),
		("VtokenMinting", "Redeemed") => Some("🍰"),
		("VoterList", "Rebagged") => Some("🤖"),
		("VoterList", "ScoreUpdated") => Some("✒️"),
		("Vesting", "VestingCompleted") => Some("😋"),
		("XcmpQueue", "XcmpMessageSent") => Some("📩"),
		("XTokens", "TransferredMultiAssets") => Some("🔮"),
		("XcmPallet", "Attempted") => Some("⚙️"),
		("XcmpQueue", "Success") => Some("👍"),
		("Xyk", "AssetsSwapped") => Some("💱"),
		("Xyk", "LiquidityBurned") => Some("🔥"),
		("XcmpQueue", "Fail") => Some("⚠️"),
		("ZenlinkProtocol", "LiquidityAdded") => Some("📈"),
		("ZenlinkProtocol", "AssetSwap") => Some("💱"),
		_ => None
	}
}

/// Represents a polkadot or parachain extrinsic as an emoji.
/// (Obviously this is only indicative and what the extrinsic actually does
/// depends on the definition of that parachain's runtime.)
///
/// These can't be represented as 'char' because some emojis span more
/// than one codepoint.
pub fn extrinsic_emoji(pallet: &str, variant: &str) -> Option<&'static str> {
	match (pallet, variant) {
		("AcalaOracle", "feed_values") => Some("🔮"),
		("AuthorInherent", "kick_off_authorship_validation") => Some("🕵️"),
		("AMM", "add_liquidity") => Some("📈"),
		("AMM", "remove_liquidity") => Some("📉"),
		("AMMRoute", "swap_exact_tokens_for_tokens") => Some("💱"),
		("AMMRoute", "swap_tokens_for_exact_tokens") => Some("💱"),
		("Balances", "transfer") => Some("🔀"),
		("Balances", "transfer_keep_alive") => Some("🔀"),
		("Balances", "transfer_all") => Some("🔀"),
		("Currencies", "transfer") => Some("🔀"),
		("ConvictionVoting", "vote") => Some("🔮"),
		("ChainBridge", "acknowledge_proposal") => Some("🔮"),	
		("Datalog", "record") => Some("✒️"),
		("DappsStaking", "bond_and_stake") => Some("🔒"),
		("DappsStaking", "set_reward_destination") => Some("️‍🔧"),
		("DappsStaking", "claim_staker") => Some("🔮"),
		("Democracy", "vote") => Some("☑"),
		("Dex", "swap_with_exact_supply") => Some("💱"),
		("Ethereum", "transact") => Some("⚙️"),
		("EVM", "call") => Some("🧠"),
		("EVM", "withdraw") => Some("💰"),
		("FuelTanks", "dispatch") => Some("🔮"),
		("FuelTanks", "add_account") => Some("️‍🪪"),
		("Farming", "withdraw") => Some("💰"),
		("Farming", "withdraw_lp") => Some("📉"),
		("Farming", "withdraw_claim") => Some("️‍🧑‍🌾"),
		("Farming", "deposit") => Some("️‍🧑‍🌾"),
		("ImOnline", "heartbeat") => Some("️‍💓"),
		("Identity", "set_identity") => Some("️‍🪪"),
		("Incentives", "claim_rewards") => Some("️‍😋"),
		("Lighthouse", "set") => Some("🔮"),
		("LiquidStaking", "set_staking_ledger") => Some("✒️"),
		("Loans", "borrow") => Some("💰"),
		("Loans", "mint") => Some("️‍💲"),
		("Loans", "claim_reward") => Some("️‍😋"),
		("Loans", "redeem") => Some("💰"),
		("MultiTokens", "batch_transfer") => Some("🔀"),
		("Multisig", "as_multi") => Some("️‍👥"),
		("NominationPools", "bond_extra") => Some("🔒"),
		("NominationPools", "claim_payout") => Some("🔓"),
		("Nft", "transfer") => Some("️‍👩‍🎨"),
		("NominationPools", "join") => Some("🔮"),
		("Oracle", "set_price_unsigned") => Some("🔮"),
		("Oracle", "feed_values") => Some("🔮"),
		("PolkadotXcm", "limited_reserve_transfer_assets") => Some("🔀"),
		("ParaInherent", "enter") => Some("⚙️"),
		("Pablo", "add_liquidity") => Some("📈"),
		("Pablo", "swap") => Some("🔀"),
		("ParachainStaking", "delegator_bond_more") => Some("🔒"),
		("ParachainSystem", "set_validation_data") => Some("⚙️"),
		("PhalaBasePool", "remove_unused_property") => Some("️‍🔥"),
		("PhalaWrappedBalances", "wrap") => Some("🔒"),
		("PhalaWrappedBalances", "unwrap") => Some("🔓"),
		("PhalaWrappedBalances", "unwrap_all") => Some("🔓"),
		("PhalaStakePoolv2", "start_computing") => Some("️‍🧠"),
		("PhalaStakePoolv2", "claim_owner_rewards") => Some("️🥕"),
		("PhalaStakePoolv2", "withdraw") => Some("💰"),
		("PhalaStakePoolv2", "set_cap") => Some("✒️"),
		("PhalaMq", "sync_offchain_message") => Some("📨"),
		("PhalaRegistry", "register_worker") => Some("⚙️"),
		("Proxy", "proxy") => Some("👻"),
		("Randomness", "set_babe_randomness_results") => Some("🎲"),
		("RWS", "call") => Some("⚙️"),
		("Referenda", "refund_submission_deposit") => Some("💰"),
		("Staking", "nominate") => Some("🔮"),
		("Staking", "bond") => Some("🔒"),
		("Staking", "bond_extra") => Some("🔮"),
		("Staking", "withdraw_unbonded") => Some("💰"),
		("Session", "set_keys") => Some("🗝️"),
		("Staking", "unbond") => Some("🔓"),
		("Staking", "set_payee") => Some("👤"),
		("Staking", "payout_stakers") => Some("💎"),
		("Staking", "chill") => Some("❄️"),
		("System", "remark") => Some("️‍🗨️"),
		("Timestamp", "set") => Some("🕘"),
		("TransactionPayment", "TransactionFeePaid") => Some("️‍🫴"),
		("Utility", "batch_all") => Some("📶"),
		("Utility", "batch") => Some("📶"),
		("Utility", "force_batch") => Some("📶"),
		("Unique", "set_token_properties") => Some("✒️"),
		("Unique", "create_item") => Some("🎨"),
		("Vesting", "claim") => Some("🥕"),
		("Vesting", "claim_for") => Some("🥕"),
		("Vesting", "vest") => Some("🥕"),
		("XcmPallet", "limited_teleport_assets") => Some("🔀"),
		("XcmPallet", "reserve_transfer_assets") => Some("🔀"),
		("XTokens", "transfer") => Some("🔀"),
		("ZenlinkProtocol", "swap_exact_assets_for_assets") => Some("💱"),
		("Xyk", "sell_asset") => Some("💱"),
		("Xyk", "burn_liquidity") => Some("️‍🔥"),
		("Xyk", "claim_rewards_v2") => Some("🥕"),
		_ => None
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	#[test]
	fn event() {
		assert_eq!(event_emoji("Democracy", "Voted"), Some("☑"));
		assert_eq!(event_emoji("Democracy", "not exist"), None);
	}

	#[test]
	fn extrinsic() {
		assert_eq!(extrinsic_emoji("Timestamp", "set"), Some("🕘"));
		assert_eq!(extrinsic_emoji("Timestamp", "not exist"), None);
	}
}
